export const ACTIONS = {
  DISPLAY_ALERT: "DISPLAY_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
  // refactor
  SETUP_USER_BEGIN: "SETUP_USER_BEGIN",
  SETUP_USER_SUCCESS: "SETUP_USER_SUCCESS",
  SETUP_USER_ERROR: "SETUP_USER_ERROR",
};
