export const ACTIONS = {
  DISPLAY_ALERT: "DISPLAY_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
  SETUP_USER_BEGIN: "SETUP_USER_BEGIN",
  SETUP_USER_SUCCESS: "SETUP_USER_SUCCESS",
  SETUP_USER_ERROR: "SETUP_USER_ERROR",
  LOGOUT: "LOGOUT",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  UPDATE_USER_BEGIN: "UPDATE_USER_BEGIN",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
};
