export const ACTIONS = {
  DISPLAY_ALERT: "DISPLAY_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
  REGISTER_USER_BEGIN: "REGISTER_USER_BEGIN",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
};
